language: objective-c
osx_image: xcode9.2

before_install:
  - pod install

before_script:
  - export QINIU_TEST_ENV="travis"

script:
  - xcodebuild -workspace HappyDNS.xcworkspace -scheme HappyDNS_iOS -sdk iphonesimulator -configuration Release -destination 'platform=iOS Simulator,name=iPhone 5s,OS=11.2' test
  - xcodebuild -workspace HappyDNS.xcworkspace -scheme HappyDNS_Mac -sdk macosx -configuration Debug test
